version: '3'
services:
  sfl-engine:
    build: .
    container_name: cluster-engine
    volumes:
      - .:/home/app
    external_links:
      - actionmedia
    ports:
      - 5000:5000
    environment:
      - BRANCH=dev
      - VIRTUAL_HOST=cluster-engine-local.jatun.systems
    networks:
      - proxy
      - database
    depends_on:
      - redis

  redis:
    image: redis:latest

networks:
  database:
    external: true
  proxy:
    external: true
  default:
    external:
      name: actionmedia-network
